Repository justeattakeaway/JustEat.StatsD, pull requests merged in 2025-01, with the labels that each got.

#809 Fix build badges
  README.md
  package-readme.md
Labels: bug

#816 Update to xunit v3
  Directory.Build.props
  Directory.Packages.props
  src/JustEat.StatsD/JustEat.StatsD.csproj
  tests/JustEat.StatsD.Tests/EndpointLookups/CachedEndpointSourceTests.cs
  tests/JustEat.StatsD.Tests/EndpointLookups/EndPointFactoryTests.cs
  tests/JustEat.StatsD.Tests/EndpointLookups/SimpleEndpointTests.cs
  tests/JustEat.StatsD.Tests/IntegrationTests.cs
  tests/JustEat.StatsD.Tests/JustEat.StatsD.Tests.csproj
  tests/JustEat.StatsD.Tests/StatsDPublisherTests.cs
Labels: enhancement, dependencies, .NET

#818 Add GraphiteDB tags formatter
  src/JustEat.StatsD/PublicAPI.Unshipped.txt
  src/JustEat.StatsD/TagsFormatter.cs
  src/JustEat.StatsD/TagsFormatters/GraphiteDbTagsFormatter.cs
  tests/JustEat.StatsD.Tests/Utf8TagsFormatterTests.cs
  version.props
Labels: enhancement

#821 Singleton formatters
  src/JustEat.StatsD/TagsFormatter.cs
  src/JustEat.StatsD/TagsFormatters/TrailingTagsFormatter.cs
Labels: enhancement
